package com.bookstore.model;

public class Report {
    // Encapsulated fields
    private String reportID;
    private String reportType; // SALES, INVENTORY, USER_ACTIVITY
    private String generatedDate;
    private String generatedBy; // adminID
    private String content; // summary text

    // No-args constructor
    public Report() {
    }

    // Full constructor
    public Report(String reportID, String reportType, String generatedDate, String generatedBy, String content) {
        this.reportID = reportID;
        this.reportType = reportType;
        this.generatedDate = generatedDate;
        this.generatedBy = generatedBy;
        this.content = content;
    }

    // Getters and Setters
    public String getReportID() {
        return reportID;
    }

    public void setReportID(String reportID) {
        this.reportID = reportID;
    }

    public String getReportType() {
        return reportType;
    }

    public void setReportType(String reportType) {
        this.reportType = reportType;
    }

    public String getGeneratedDate() {
        return generatedDate;
    }

    public void setGeneratedDate(String generatedDate) {
        this.generatedDate = generatedDate;
    }

    public String getGeneratedBy() {
        return generatedBy;
    }

    public void setGeneratedBy(String generatedBy) {
        this.generatedBy = generatedBy;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    // Generate formatted report summary
    public String generateSummary() {
        return "=== " + reportType + " REPORT ===\n" +
                "Report ID: " + reportID + "\n" +
                "Generated: " + generatedDate + "\n" +
                "Generated By: " + generatedBy + "\n" +
                "Content:\n" + content;
    }

    @Override
    public String toString() {
        return "Report{" +
                "reportID='" + reportID + '\'' +
                ", reportType='" + reportType + '\'' +
                ", generatedDate='" + generatedDate + '\'' +
                ", generatedBy='" + generatedBy + '\'' +
                '}';
    }
}